// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4iWBWbxAwaJCOnfXoiJzQQhrdf2OUPF4',
    appId: '1:580445382085:web:0531c9a2465e6a3e1357ac',
    messagingSenderId: '580445382085',
    projectId: 'rail-signin',
    authDomain: 'rail-signin.firebaseapp.com',
    storageBucket: 'rail-signin.appspot.com',
    measurementId: 'G-VQNYGCGBPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjhsXvWf9W7Wid9VaBYn-BHmVy5fylts',
    appId: '1:580445382085:android:c1a12a57fdffd0f71357ac',
    messagingSenderId: '580445382085',
    projectId: 'rail-signin',
    storageBucket: 'rail-signin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkdF8RBu_59XTcq4zgQoK5DG8HLqrlTXc',
    appId: '1:580445382085:ios:5fb0034755f50c811357ac',
    messagingSenderId: '580445382085',
    projectId: 'rail-signin',
    storageBucket: 'rail-signin.appspot.com',
    androidClientId: '580445382085-l0h7p95j00eqon212ts2ua3kijpfjvdp.apps.googleusercontent.com',
    iosClientId: '580445382085-e4r00kr7ef0ddjia5pcn5itoshvsfr67.apps.googleusercontent.com',
    iosBundleId: 'com.example.rail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkdF8RBu_59XTcq4zgQoK5DG8HLqrlTXc',
    appId: '1:580445382085:ios:5fb0034755f50c811357ac',
    messagingSenderId: '580445382085',
    projectId: 'rail-signin',
    storageBucket: 'rail-signin.appspot.com',
    androidClientId: '580445382085-l0h7p95j00eqon212ts2ua3kijpfjvdp.apps.googleusercontent.com',
    iosClientId: '580445382085-e4r00kr7ef0ddjia5pcn5itoshvsfr67.apps.googleusercontent.com',
    iosBundleId: 'com.example.rail',
  );
}
